dns_domain: "prod.maskedadmins.com"
#sat6_default_org: redhatlab
sat6_default_org: Redhat_Lab
sat6_default_location: AWS_RTO
sat6_default_hostcollection: RHEL_7_x86_64
sat6_default_hostgroup: "RHEL_7_x86_64_Hostgroup"
sat6_default_domain: "prod.maskedadmins.com"
sat6_default_subnet: "default"
sat6_default_environment: "production"
tower_key: dc7c0b52cd29cacceb8d3571257801ea
tower_server: tower.dev.maskedadmins.com
tower_jobid: 287
sat6:
  compute_resources:
#    - name: 'OSP8 Redhat Lab'
#      description: 'Openstack 8 Redhat Lab'
#      user: 'dtaylor'
#      pass: "{{ ipmi_pass }}"
#      tenant: "Redhat Lab"
#      controller: "{{ osp8_controller }}"
#      url: "http://{{ osp8_controller }}:5000/v2.0/tokens"
#    - name: 'OSP8 Masked Admins'
#      description: 'Openstack 8 Masked_Admins'
#      user: dtaylor
#      pass: "{{ ipmi_pass }}"
#      tenant: "Masked_Admins"
#      controller: "{{ osp8_controller }}"
#      url: "http://{{ osp8_controller }}:5000/v2.0/tokens"
    - name: 'OSP13 Redhat Lab'
      description: 'Openstack 13'
      user: dtaylor
      pass: redhat123
      tenant: "Redhat_Lab"
      controller: "{{ osp10_controller }}"
      url: "http://{{ osp10_controller }}:5000/v3"
      OS_PROJECT_DOMAIN_ID: "default"
      OS_USER_DOMAIN_ID: "default"
  environments:
    - name: 'Development'
      prior: 'Library'
    - name: 'Testing'
      prior: 'Development'
    - name: 'Production'
      prior: 'Testing'
  locations:
    - "Private_Cloud"
#        - "Legacy_Servers"
#        - "Public_Cloud"
  domains:
    - "dev.maskedadmins.com"
    - "test.maskedadmins.com"
    - "prod.maskedadmins.com"
    - "strg.maskedadmins.com"
  subnets:
    - name: "Dev_103"
      gw: "10.55.103.1"
      network: "10.55.103.0"
      mask: "255.255.255.0"
      dns: "10.55.102.5"
      domain: "dev.maskedadmins.com"
      location: "Private_Cloud"
      org: "Redhat_Lab"
    - name: "Test_104"
      gw: "10.55.104.1"
      network: "10.55.104.0"
      mask: "255.255.255.0"
      dns: "10.55.102.5"
      domain: "test.maskedadmins.com"
      location: "Private_Cloud"
      org: "Redhat_Lab"
    - name: "Storage_105"
      gw: "10.55.105.1"
      network: "10.55.105.0"
      mask: "255.255.255.0"
      dns: "10.55.102.5"
      domain: "strg.maskedadmins.com"
      location: "Private_Cloud"
      org: "Redhat_Lab"
    - name: "Prod_106"
      gw: "10.55.106.1"
      network: "10.55.106.0"
      mask: "255.255.255.0"
      dns: "10.55.102.5"
      domain: "prod.maskedadmins.com"
      location: "Private_Cloud"
      org: "Redhat_Lab"
  orgs:
#        - name: "Infra"
#          label: "infrastructure"
#          description: "Our example infra organization for managing content."
#          locations:
#            - 'Legacy_Servers'
#            - 'Private_Cloud'
#            - 'Public_Cloud'
#          domains:
#            - "dev.maskedadmins.com"
#            - "test.maskedadmins.com"
#            - "prod.maskedadmins.com"
#            - "strg.maskedadmins.com"
#          subnets:
#            - "Dev_103"
#            - "Test_104"
#            - "Storage_105"
#            - "Prod_106"
    - name: "Redhat_Lab"
      label: "redhatlab"
      description: "Our example sub organization for managing content."
      locations:
        - 'Private_Cloud'
      domains:
        - "dev.maskedadmins.com"
        - "test.maskedadmins.com"
        - "prod.maskedadmins.com"
        - "strg.maskedadmins.com"
      subnets:
        - "Dev_103"
        - "Test_104"
        - "Storage_105"
        - "Prod_106"
sat6_manifest: "manifest_sat6.zip"
sat6_pool_ids: ['']
sat6_enabled_products:
  - "Red Hat Enterprise Linux Server"
  - "Red Hat Enterprise Linux Fast Datapath"
  - "Red Hat OpenStack"
  - "Red Hat OpenShift Container Platform"
sat6_enabled_repos:
  - name: "Red Hat Enterprise Linux 7 Server (RPMs)"
    product: "Red Hat Enterprise Linux Server"
  - name: "Red Hat Enterprise Linux 7 Server (Kickstart)"
    product: "Red Hat Enterprise Linux Server"
  - name: "Red Hat Enterprise Linux 7 Server - RH Common (RPMs)"
    product: "Red Hat Enterprise Linux Server"
  - name: "Red Hat Enterprise Linux 7 Server - Optional (RPMs)"
    product: "Red Hat Enterprise Linux Server"
  - name: "Red Hat Enterprise Linux Fast Datapath (RHEL 7 Server) (RPMs)"
    product: "Red Hat Enterprise Linux Fast Datapath"
sat6_enabled_repos_tools:
  - name: "Red Hat Satellite Tools 6.2 (for RHEL 7 Server) (RPMs)"
    product: "Red Hat Enterprise Linux Server"
  - name: "Red Hat Enterprise Linux 7 Server - Extras (RPMs)"
    product: "Red Hat Enterprise Linux Server"
sat6_enabled_repos_openstack:
  - name: "Red Hat OpenStack Platform 10 for RHEL 7 (RPMs)"
    product: "Red Hat OpenStack"
  - name: "Red Hat OpenStack Platform 10 Developer Tools for RHEL 7 (RPMs)"
    product: "Red Hat OpenStack"
sat6_enabled_repos_openshift:
  - name: "Red Hat OpenShift Container Platform 3.5 (RPMs)"
    product: "Red Hat OpenShift Container Platform"
sat6_url: "https://{{ ansible_fqdn }}/"
sat6_user: "admin"
sat6_pass: "redhat123"
fusor_installer_lease_from: 10.55.102.200
fusor_installer_lease_to: 10.55.102.211
