---
- hosts: aap25-controller*
  tasks:
  - name: "Add private builder ssh key"
    template:
      src: privatesshkey.j2
      dest: "/root/.ssh/ansiblesvc.key"
      owner: root
      group: root
      mode: 0400
    become: yes

  - name: "Config ssh client"
    template:
      src: ssh-config.j2
      dest: "/root/.ssh/config"
      owner: root
      group: root
      mode: 0400
    become: yes

  - name: "Get short hostname"
    shell: |
      hostname --short
    register: shortname
  
  - name: "Set the short hostname fact"
    set_fact:
      shorthostname: "{{ shortname.stdout }}"

  - name: "Start install, probably will fail"
    shell: |
      echo "see /root/ansible-setup-output.log for details"
      exec &> >(tee -a /root/ansible-setup-output.log)
      # bug: add port 8443 to firewall config
      ssh root@aap25-gw "systemctl start firewalld; firewall-cmd --add-port 8443/tcp --permanent --reload"
      ./setup.sh
    become: true
    args:
      executable: /bin/bash
      chdir: /root/ansible-automation-platform-setup-bundle-2.5-11-x86_64

  - name: "Retart install, should succeed"
    shell: |
      echo "see /root/ansible-setup-output.log for details"
      exec &> >(tee -a /root/ansible-setup-output.log)
      # bug: the certs need to be accepted
      for i in gw controller hub eda exec db;
      do
        scp /etc/pki/ca-trust/source/anchors/ansible-automation-platform-managed-ca-cert.crt root@aap25-${i}:/etc/pki/ca-trust/source/anchors/
        ssh root@aap25-${i} "update-ca-trust extract"; 
      done
      ./setup.sh
    become: true
    args:
      executable: /bin/bash
      chdir: /root/ansible-automation-platform-setup-bundle-2.5-11-x86_64
