---
- hosts: aap25-*
  tasks:
  - name: "Get short hostname"
    shell: |
      hostname --short
    register: shortname
  
  - name: "Set the short hostname fact"
    set_fact:
      shorthostname: "{{ shortname.stdout }}"

  - name: "yum update -y"
    shell: "yum update -y"
    become: true

  - name: "Reboot in one minute"
    shell: |
      shutdown -r +1 || true
    become: true
    args:
      executable: /bin/bash

  - name: "Wait 2 to 11 mins for host to reboot"
    wait_for:
      port: 22
      host: "{{ shorthostname}}.{{ dns_domain }}"
      #host: "{{ ansible_ssh_host | default(inventory_hostname) }}"
      #search_regex: OpenSSH
      delay: 120
      timeout: 660
    delegate_to: localhost
    become: false
