---
- hosts: aap25-controller*
  tasks:
  - name: "Add private builder ssh key"
    template:
      src: privatesshkey.j2
      dest: "/root/.ssh/ansiblesvc.key"
      owner: root
      group: root
      mode: 0400
    become: yes

  - name: "Config ssh client"
    template:
      src: ssh-config.j2
      dest: "/root/.ssh/config"
      owner: root
      group: root
      mode: 0400
    become: yes

  - name: "Get short hostname"
    shell: |
      hostname --short
    register: shortname
  
  - name: "Set the short hostname fact"
    set_fact:
      shorthostname: "{{ shortname.stdout }}"

  - name: "copy up the entitlement manifest"
    copy:
      src: manifest.zip
      dest: /root/ansible-automation-platform-setup-bundle-2.5-11-x86_64/manifest.zip

  - name: Load vault decrypted manifest into variable
    slurp:
      src: "/root/ansible-automation-platform-setup-bundle-2.5-11-x86_64/manifest.zip"
    register: manifest_file

  - name: "Start install, probably will fail after 23 mins"
    shell: |
      echo "see /root/ansible-setup-output.log for details"
      exec &> >(tee -a /root/ansible-setup-output.log)
      # bug: add port 8443 to firewall config
      ssh root@aap25-gw "systemctl start firewalld; firewall-cmd --add-port 8443/tcp --permanent --reload"
      ./setup.sh
    become: true
    ignore_errors: true
    args:
      executable: /bin/bash
      chdir: /root/ansible-automation-platform-setup-bundle-2.5-11-x86_64
      creates: /root/ansible-automation-platform-setup-bundle-2.5-11-x86_64/.installsuccess

  - name: "Retart install, populate EE and collections. gw will be accessible in 30 mins, should succeed after 120 mins"
    shell: |
      echo "see /root/ansible-setup-output.log for details"
      exec &> >(tee -a /root/ansible-setup-output.log)
      # bug: the certs need to be accepted
      for i in gw hub eda exec db;
      do
        scp /etc/pki/ca-trust/source/anchors/ansible-automation-platform-managed-ca-cert.crt root@aap25-${i}:/etc/pki/ca-trust/source/anchors/
        ssh root@aap25-${i} "update-ca-trust extract"; 
      done
      ./setup.sh && touch /root/ansible-automation-platform-setup-bundle-2.5-11-x86_64/.installsuccess
    become: true
    ignore_errors: true
    args:
      executable: /bin/bash
      chdir: /root/ansible-automation-platform-setup-bundle-2.5-11-x86_64
      creates: /root/ansible-automation-platform-setup-bundle-2.5-11-x86_64/.installsuccess

  - name: Post manifest file and accept the EULA
    uri:
      url: https://aap25-gw.tfound.org/api/v2/config/
      method: POST
      user: admin
      password: "{{ tower_pass }}"
      body: '{ "eula_accepted": true, "manifest": "{{ manifest_file.content }}" }'
      body_format: json
      validate_certs: false
      force_basic_auth: true

