---
- hosts: aap25-controller*
  tasks:
  - name: "Add private builder ssh key"
    template:
      src: privatesshkey.j2
      dest: "/root/.ssh/ansiblesvc.key"
      owner: root
      group: root
      mode: 0400
    become: yes

  - name: "Config ssh client"
    template:
      src: ssh-config.j2
      dest: "/root/.ssh/config"
      owner: root
      group: root
      mode: 0400
    become: yes

  - name: "Get short hostname"
    shell: |
      hostname --short
    register: shortname
  
  - name: "Set the short hostname fact"
    set_fact:
      shorthostname: "{{ shortname.stdout }}"

  - name: "Start install"
    shell: |
      echo "see /root/ansible-setup-output.log for details"
      exec &> >(tee -a /root/ansible-setup-output.log)
      ./setup.sh
    become: true
    args:
      executable: /bin/bash
      chdir: /root/ansible-automation-platform-setup-bundle-2.5-11-x86_64
