- hosts: all
  environment:
    # these can be ansible tower/awx credentials
    AWS_ACCESS_KEY_ID: "{{ AWS_ACCESS_KEY_ID }}"
    AWS_SECRET_KEY: "{{ AWS_SECRET_KEY }}"
  tasks:
  - ec2_instance_info:
      #filters:
      #  "tag:Name": dataylor
      region: us-east-1
    register: results

  - debug:
      msg: "{{ results.instances.tags }} is using AMI {{ results.instances.image_id }}"
