- hosts: localhost
  vars:
    region: us-east-1
  environment:
    AWS_ACCESS_KEY_ID: "{{ TFOUND_AWS_ACCESS_KEY_ID }}"
    AWS_SECRET_KEY: "{{ TFOUND_AWS_SECRET_KEY }}"
  tasks:
  - name: Gather info on all the AWS accounts in a region
    ec2_instance_info:
      region: "{{ region }}"
    register: results

  - name: Get the info on the AMIs
    ec2_ami_info:
      image_ids: "{{ item }}"
      region: "{{ region }}"
    register: amiinfo
    loop: "{{ results.instances | map(attribute='image_id') | list | unique }}"

  - name: Generate the csv file in /tmp/amis.csv
    template:
      src:  "amis.csv.j2"
      dest: /tmp/amis.csv

  - name: Generate the csv file in /tmp/amiinfo.csv
    template:
      src:  "amiinfo.csv.j2"
      dest: /tmp/amiinfo.csv

  - name: get the contents of the files
    shell: |
      echo "amsi.csv ============="
      cat /tmp/amis.csv
      echo "amiinfo.csv =========="
      cat /tmp/amiinfo.csv
    register: output

  - name: show the contents of the files
    debug:
      var: output.stdout_lines
