- hosts: all
  vars:
    images: []
  environment:
    AWS_ACCESS_KEY_ID: "{{ AWS_ACCESS_KEY_ID }}"
    AWS_SECRET_KEY: "{{ AWS_SECRET_KEY }}"
  tasks:
  - ec2_instance_info:
      #filters:
      #  "tag:Name": dataylor
      region: us-east-1
    register: results

#  - set_fact:
#      images: "{{ images | combine( { key: value } ) }}"
#    vars:
#      key: "name"
#      value: "{{item.tags.Name }}"
#    loop: "{{ results.instances }}"
#
#  - set_fact:
#      images: "{{ images | combine( { key: value } ) }}"
#    vars:
#      key: "ami"
#      value: "{{item.image_id }}"
#    loop: "{{ results.instances }}"

  - debug:
      msg:  "Image item.tags.Name }} is using AMI {{ item.image_id }}"
    loop: "{{ results.instances }}"
    no_log: True
