---
- name: Reset the Tang Server Inventory Groups
  hosts: localhost
  gather_facts: no
  tasks:
  - include: sat6-tower-clean-include.yml
    loop:
    - 'tang-servers'
    loop_control:
      loop_var: group_inventory

