# we received a DHCPACK, maybe a new device on the network
- name: Handle Network Events
  hosts: lab-services
  #connection: local
  gather_facts: no
  vars:
   msgpayload: "not set"
   msghost: "not set"
   zenosshost: "not set"
   zenossuser: "not set"
   zenosspass: "not set"
  tasks:
  - name: block for network scan
    block:
    - name: grab the ip address
      set_fact:
        hostip: "{{ msgpayload | split(' ') }}"

    - name: see if the ip has a reverse dns record
      ansible.builtin.shell: |
        /usr/bin/dig -x {{ hostip[5] }}
      args:
        executable: /bin/bash
      register: ipchk

    - name: output of ip dns check
      debug:
        var: ipchk.stdout_lines

  - name: block for dns scan
    block:
    - name: grab the hostname from dns
      set_fact:
        #hostname: "{{ (ipchk.stdout_lines[13] | split('\t'))[3] | trim('.') }}"
        hostname: "{{ (ipchk.stdout_lines[13] | | regex_search('PTR\\t(*.).tfound.org.$') | trim('.') }}"
    when:
      - "'DHCPACK' in msgpayload"

    rescue:
    - name: need to add reverse dns for this one
      debug:
        msg: "add reverse dns here"

  - name: block for network scan
    block:
    - name: see if the hostname has a dns record
      ansible.builtin.shell: |
        dig any {{ hostname }}
      args:
        executable: /bin/bash
      register: hostchk

    - name: output of hostname check
      debug:
        var: hostchk.stdout_lines

    - name: scan the ip
      ansible.builtin.shell: |
        /usr/bin/nmap -sS -Pn -T5 -p- --open {{ hostip[5] }}
      register: nmapchk
      args:
        executable: /bin/bash
      become: yes

    - name: output of ip scan
      debug:
        var: nmapchk.stdout_lines

    - name: wag the tail light
      ansible.builtin.shell: |
        nohup /home/pi/toggleled.sh &
      async: 1
      poll: 0
      args:
        executable: /bin/bash
      become: yes
      delegate_to: trashcanpi

    - name: pet the cat motor
      ansible.builtin.shell: |
        nohup python /home/pi/testmotor.py &
      async: 1
      poll: 0
      args:
        executable: /bin/bash
      become: yes
      delegate_to: trashcanpi

    - name: Add to monitoring
      ansible.builtin.uri:
        url: "{{ zenosshost }}"
        user: "{{ zenossuser }}"
        password: "{{ zenosspass }}"
        method: POST
        body:
        - action: DeviceRouter
          method: addDevice
          data:
          - deviceName: "{{ hostname }}"
            deviceClass: "/Discovered"
            collector: localhost
            model: true
            title: ""
            productionState: 1000
            priority: 3
            snmpCommunity: TFOUNDRO
            snmpPort: 161
            tag: ""
            rackSlot: "vmware"
            serialNumber: "0"
            hwManufacturer: "vmware"
            hwProductName: "vmware"
            osManufacturer: "Redhat"
            osProductName: "Redhat"
            comments: "added by ansible eda"
          tid: 1
        force_basic_auth: yes
        status_code: 200
        body_format: json
    when:
      - "'DHCPACK' in msgpayload"

  - name:
    debug:
      msg: "host: {{ msghost }}, payload: {{ msgpayload }}"

