# we received a DHCPACK, maybe a new device on the network
- name: Handle Network Events
  hosts: lab-services
  #connection: local
  gather_facts: no
  vars:
    msgpayload: "not set"
    msghost: "not set"
    zenosshost: "not set"
    zenossuser: "not set"
    zenosspass: "not set"
    dns_key_name: "not set"
    dns_key: "not set"
    dns_server: "not set"
    dns_domain: "not set"
    ttl: "3600"
  tasks:
  - name: block for reverse dns
    block:
    - name: grab the ip address
      set_fact:
        hostip: "{{ msgpayload | split(' ') }}"

    - name: see if the ip has a reverse dns record
      ansible.builtin.shell: |
        /usr/bin/dig -x {{ hostip[5] }}
      args:
        executable: /bin/bash
      register: ipchk

    - name: output of ip dns check
      debug:
        var: ipchk.stdout_lines

  - name: block for hostname fact
    block:
    - name: grab the hostname from dns
      set_fact:
        #hostname: "{{ (ipchk.stdout_lines[13] | split('\t'))[3] | trim('.') }}"
        hostname: "{{ ipchk.stdout_lines[13] | regex_search('PTR\t(.*).tfound.org.$') | replace('PTR\t','') | trim('.') }}"
    when:
      - "'DHCPACK' in msgpayload"

    always:
    - name: need to add reverse dns for this one
      ansible.builtin.fail:
        msg: "add reverse dns here"
      when: hostname is not defined

  - name: block for dns
    block:
    - name: see if the hostname has a dns record
      ansible.builtin.shell: |
        dig any {{ hostname }}
      args:
        executable: /bin/bash
      register: hostchk

    - name: output of dns check
      debug:
        var: hostchk.stdout_lines

    - name: Add TXT record if missing
      community.general.nsupdate:
        key_name: "{{ dns_key_name }}"
        key_secret: "{{ dns_key }}"
        server: "{{ dns_server }}"
        zone: "{{ dns_domain }}"
        record: "{{ hostname | replace('.' + dns_domain,'') }}"
        type: "TXT"
        ttl: "{{ ttl }}"
        #value: ["{{ macid }}", "{{ conntype }}", "{{ device_model }}", "{{ ssid }}",  "added by ansible {{ ansible_date_time.iso8601 }}"]
        value: ["added: by ansible eda {{ ansible_date_time.iso8601 }}"]
      when: 
        - hostchk is defined
        - "'by ansible' not in hostchk.stdout"

    - name: Add PTR record if missing
      community.general.nsupdate:
        key_name: "{{ dns_key_name }}"
        key_secret: "{{ dns_key }}"
        server: "{{ dns_server }}"
        record: "{{ hostip[5] | ansible.netcommon.ipaddr('revdns') }}"
        type: "PTR"
        value: "{{ hostname }}."
        ttl: "{{ ttl }}"
        state: present
      when: 
        - hostname is defined
        - ipchk is defined
        - "'NXDOMAIN' in ipchk.stdout"
    when:
      - hostname is defined

  - name: block for network scan
    block:
    - name: scan the ip
      ansible.builtin.shell: |
        /usr/bin/nmap -sS -Pn -T5 -p- --open {{ hostip[5] }}
      register: nmapchk
      args:
        executable: /bin/bash
      become: yes

    - name: output of ip scan
      debug:
        var: nmapchk.stdout_lines

    - name: wag the tail light
      ansible.builtin.shell: |
        nohup /home/pi/toggleled.sh &
      async: 1
      poll: 0
      args:
        executable: /bin/bash
      become: yes
      delegate_to: trashcanpi

    - name: pet the cat motor
      ansible.builtin.shell: |
        nohup python /home/pi/testmotor.py &
      async: 1
      poll: 0
      args:
        executable: /bin/bash
      become: yes
      delegate_to: trashcanpi
    when:
      - "'by ansible' not in hostchk.stdout"

  - name: block for monitoring
    block:
#      #get
#      #{"action":"DeviceRouter","method":"getDevices","data":[{"uid":"/zport/dmd/Devices","keys":["name","ipAddress","uid","productionState","events","ipAddressString","pythonClass"],"params":{"name":"test123"},"page":1,"start":0,"limit":100,"sort":"name","dir":"ASC"}],"type":"rpc","tid":14}
#      #response
#      #{
#    "uuid": "5f0ac3c8-14d0-484e-bca6-48496575f53f",
#    "action": "DeviceRouter",
#    "result": {
#        "totalCount": 1,
#        "hash": "1",
#        "success": true,
#        "devices": [
#            {
#                "ipAddressString": "10.55.102.105",
#                "name": "test123.tfound.org",
#                "productionState": 1000,
#                "uid": "/zport/dmd/Devices/Server/Linux/devices/test123.tfound.org",
#                "ipAddress": 171402857,
#                "events": {
#                    "info": {
#                        "count": 0,
#                        "acknowledged_count": 0
#                    },
#                    "clear": {
#                        "count": 0,
#                        "acknowledged_count": 0
#                    },
#                    "warning": {
#                        "count": 1,
#                        "acknowledged_count": 0
#                    },
#                    "critical": {
#                        "count": 0,
#                        "acknowledged_count": 0
#                    },
#                    "error": {
#                        "count": 0,
#                        "acknowledged_count": 0
#                    },
#                    "debug": {
#                        "count": 0,
#                        "acknowledged_count": 0
#                    }
#                },
#                "pythonClass": "Products.ZenModel.Device"
#            }
#        ]
#    },
#    "tid": 14,
#    "type": "rpc",
#    "method": "getDevices"
#}
    - name: Check if already monitored
      ansible.builtin.uri:
        url: "{{ zenosshost }}"
        url_username: "{{ zenossuser }}"
        url_password: "{{ zenosspass }}"
        method: POST
        body:
        - action: DeviceRouter
          method: getDevices
          data:
            - uid: /zport/dmd/Devices
              keys:
                - name
                - ipAddress
                - uid
                - productionState
                - events
                - ipAddressString
                - pythonClass
              params:
                ipAddress: "{{ hostip[5] }}"
              page: 1
              start: 0
              limit: 100
              sort: name
              dir: ASC
          type: rpc
          tid: 1
        force_basic_auth: yes
        status_code: 200
        body_format: json
      register: isitmonitored
    
    - name: debug monitoring check
      debug:
        var: isitmonitored.json.result

    - name: Add to monitoring if missing
      ansible.builtin.uri:
        url: "{{ zenosshost }}"
        url_username: "{{ zenossuser }}"
        url_password: "{{ zenosspass }}"
        method: POST
        body:
        - action: DeviceRouter
          method: addDevice
          data:
          - deviceName: "{{ hostip[5] }}"
            deviceClass: "/Discovered"
            collector: localhost
            model: true
            title: "{{ hostname }}"
            productionState: 1000
            priority: 3
            snmpCommunity: TFOUNDRO
            snmpPort: 161
            tag: ""
            rackSlot: "vmware"
            serialNumber: "0"
            hwManufacturer: "vmware"
            hwProductName: "vmware"
            osManufacturer: "Redhat"
            osProductName: "Redhat"
            comments: "added by ansible eda"
          tid: 2
        force_basic_auth: yes
        status_code: 200
        body_format: json
      when:
        - isitmonitored.json.result.totalCount | int == 0
    when:
      - hostname is defined

  - name:
    debug:
      msg: "host: {{ msghost }}, payload: {{ msgpayload }}"

