# we received a DHCPACK, maybe a new device on the network
- name: Handle Network Events
  hosts: lab-services
  #connection: local
  gather_facts: no
  vars:
   msgpayload: "not set"
   msghost: "not set"
  tasks:
  - name: block for network scan
    block:
    - name: grab the ip address
      set_fact:
        hostip: "{{ msgpayload | split(' ') }}"

    - name: see if the ip has a reverse dns record
      ansible.builtin.shell: |
        /usr/bin/dig -x {{ hostip[5] }}
      args:
        executable: /bin/bash
      register: ipchk

    - name: output of ip dns check
      debug:
        var: ipchk.stdout

    - name: see if the hostname has a dns record
      ansible.builtin.shell: |
        dig any {{ hostip[9] }}
      args:
        executable: /bin/bash
      register: hostchk
      when:
        - hostip[9] != 'via'

    - name: output of hostname check
      debug:
        var: hostchk.stdout

    - name: scan the ip
      ansible.builtin.shell: |
        nmap -sS -Pn -T5 -p- -vv {{ hostip[9] }}
      args:
        executable: /bin/bash
      become: yes
    when:
      - "'DHCPACK' in msgpayload"

  - name:
    debug:
      msg: "host: {{ msghost }}, payload: {{ msgpayload }}"

