---
- name: "Scale an Openshift app to the desired size"
  hosts: all
  vars:
    ose_app: "simplephp"
    ose_user: "admin"
    ose_pass: "redhat123"
    ose_project: redhat-lab
    ose_replicas: 3
  tasks:
    - name: "Scale {{ ose_app }} to {{ ose_replicas }} replicas"
      shell: |
        oc login -u {{ ose_user }} -p {{ ose_pass }}
        oc project {{ ose_project }}
        oc scale dc {{ ose_app }} --replicas={{ ose_replicas }}
      become: true
