---
- name: "Register a host with the correct Satellite 6 Load balancer"
  vars:
    sat6_clients: "all:!satellite-server:!capsules:!capsule-lb"
  hosts: "{{ sat6_clients }}"
  become: yes
  roles:
    - satellite-clients
    - webconsole
  tasks:
    - name: "lets smoke test"
      shell: curl http://localhost/

