---
- name: wait for repo sync to complete
  hosts: satellite-server
  gather_facts: no
  vars:
    task: Synchronize repository 
    attempts: 120
    delay: 60
  tasks:
  - name: Loop over hammer task command until no running sync tasks
    shell: hammer task list | grep "{{ task }}" || true
    register: hammertasks
    retries: "{{ attempts }}"
    delay: "{{ delay }}"
    until: hammertasks.stdout.find("running") == -1
