---
- name: "Register a host with Satellite 6"
  hosts: all:!sat6*
  vars:
    sat6:
      url: "sat6.dev.maskedadmins.com"
      user: "admin"
      pass: "redhat123"
      org: Redhat_Lab
      hostgroup: "RHEL_7_x86_64_Hostgroup for dev.maskedadmins.com RedHat 7.3"
      location: "Private_Cloud"
      environment: "development"
      activation_key: "Redhat_Lab-development-key"
  tasks:
    - name: "Get the bootstrap python script"
      get_url:
        url: "http://{{ sat6['url'] }}/pub/bootstrap.py"
        dest: /opt/bootstrap.py

    - name: "Run the satellite bootstrap script"
      shell: |
        chmod +x /opt/bootstrap.py
        /opt/bootstrap.py -l {{ sat6['user'] }} -p {{ sat6['pass'] }} \
        -s {{ sat6['url'] }} \
        -o "{{ sat6['org'] }}" \
        -L {{ sat6['location'] }} \
        -g "{{ sat6['hostgroup'] }}" \
        -a {{ sat6['activation_key'] }} \
        --force --add-domain --subscription-manager-args="--insecure" --rex --rex-user root
        #--force --add-domain --subscription-manager-args="--insecure" --rex --rex-user root
      become: true
      register: satbootstrap
