---
- name: "Register a host with the correct Satellite 6 Load balancer"
  hosts: all:!satellite-server:!capsules:!capsule-lb
  become: yes
  roles:
    - satellite-clients
    - webconsole
  tasks:
    - name: "lets smoke test"
      shell: curl http://localhost/

