---
- name: Firstboot configuration tasks
  hosts: all
  roles:
    - firstboot-setup

- name: Firstboot configuration tasks
  hosts: all:!aap25*
  roles:
    - firstboot-selinux
    - firstboot-accounts

- name: Firstboot configuration tasks
  hosts: aap25*
  roles:
    - firstboot-accounts

- name: Satellite clients to access content
  hosts: all:!sat6*:!satellite*:!management*
  become: yes
  roles:
    - satellite-clients
    - insights

- name: Firstboot network and filesystem tasks
  hosts: all
  roles:
    - firstboot-network
    - firstboot-monitor-filesystem

- name: Firstboot final tasks
  hosts: all:!aap25*
  roles:
    - firstboot
    - firstboot-terminallogging
    - tmux

- name: Firstboot configuration tasks
  hosts: logging*
  roles:
    - log-collector
    - splunk
    - lldp-client
    - snmp-client

- name: Monitoring roles
  hosts: all:!logging*
  become: yes
  roles:
    - rsyslog-client
    - lldp-client
    - snmp-client

- name: Role specific tasks
  hosts: all:!sat6*:!satellite*:haproxy*:openfire*:minikube*:!management*:!capsule*:!aap25*
  roles:
    - assignedroles

- name: Supporting roles
  hosts: all:!sat6*:!satellite*:haproxy*:openfire*:minikube*:!management*:!capsule*:!aap25*
  become: yes
  roles:
    - webconsole
#    - leapp-upgrade


- name: Create ansible build environment
  hosts: builder*
  become: yes
  roles:
    - ansible-builder

- name: Create atlanta robotics proxy
  hosts: gdc-proxy*
  become: yes
  roles:
    - haproxy-atlanta-robotics

- name: Install Jboss Standalone
  hosts: jboss*
  become: yes
  roles:
    - jboss-standalone

- name: Configure Satellite
  hosts: sat6*
  environment: "{{ sat6_environment_vars }}"
  roles:
    - satellite-server
    - satellite-oscap

- name: Configure Satellite Capsules
  hosts: capsule*:!capsule-lb*
  environment: "{{ sat6_environment_vars }}"
  roles:
    - satellite-capsule
    - satellite-oscap

- name: Configure Satellite Capsule Load Balancer
  hosts: capsule-lb*
  roles:
    - haproxy
    - snmp-client
    - rsyslog-client

- name: Configure Cloudforms Management Engine
  hosts: cloudforms*:cfme*
  roles:
    - cloudforms-server
    - firstboot
    - insights

- name: Configure Openstack Compute Nodes with HugePages, CPU pinning 
  hosts: osp10-computes
  roles:
    - { role: openstack, osp_mode: computes, cfme: false }

- name: Customize Openstack -  create networks, projects, users, and import glance images from nfs share
  hosts: osp10-controllers
  roles:
    - { role: openstack, osp_mode: controllers, cfme: true }

- name: Customize Openshift Container Platform nodes
  hosts: ose-cluster-node*
  roles:
    - { role: openshift, ocp_mode: nodes, cfme: false }

- name: Customize Openshift Container Platform with 2 additional nodes
  hosts: ose-cluster-master*
  roles:
    - { role: openshift, ocp_mode: controllers, cfme: true }

- name: Customize Ansible Tower
  hosts: tower*:10.55.102.156
  roles:
    - ansible-tower

- name: Network Bound Disk Encryption Client
  hosts: clevis*
  roles:
    - nbde-clevis-client

- name: Network Bound Disk Encryption Server
  hosts: tang-*
  roles:
    - nbde-tang-server

