---
- name: Firstboot configuration tasks
  hosts: all:!cfme*:!cloudforms*
  environment:
    # these can be ansible tower/awx credentials
    AWS_ACCESS_KEY_ID: "{{ AWS_ACCESS_KEY_ID }}"
    AWS_SECRET_KEY: "{{ AWS_SECRET_KEY }}"
  become: yes
  roles:
    - firstboot
    - insights
    - awsroles

- name: Install Jboss Standalone
  hosts: jboss*
  become: yes
  roles:
    - jboss-standalone

- name: Configure Satellite
  hosts: sat6*
  roles:
    - satellite-server

- name: Configure Satellite Capsules
  hosts: capsule*
  roles:
    - satellite-capsule

- name: Configure Satellite Capsule Load Balancer
  hosts: lb-capsule*
  roles:
    - haproxy

- name: Configure Cloudforms Management Engine
  hosts: cloudforms*:cfme*
  roles:
    - cloudforms-server
    - firstboot
    - insights

- name: Configure Openstack Compute Nodes with HugePages, CPU pinning 
  hosts: osp10-computes
  roles:
    - { role: openstack, osp_mode: computes, cfme: false }

- name: Customize Openstack -  create networks, projects, users, and import glance images from nfs share
  hosts: osp10-controllers
  roles:
    - { role: openstack, osp_mode: controllers, cfme: true }

- name: Customize Openshift Container Platform nodes
  hosts: ose-cluster-node*
  roles:
    - { role: openshift, ocp_mode: nodes, cfme: false }

- name: Customize Openshift Container Platform with 2 additional nodes
  hosts: ose-cluster-master*
  roles:
    - { role: openshift, ocp_mode: controllers, cfme: true }

- name: Customize Ansible Tower
  hosts: tower*:10.55.102.156
  roles:
    - ansible-tower

