---
- name: Firstboot configuration tasks
  hosts: all:!cfme*:!cloudforms*
  roles:
    - firstboot
    - insights
    - snmp-client
    - awsroles
    - vmwareroles

- name: Supporting roles
  hosts: all:!sat6*:!satellite*:haproxy*:openfire*:minikube*:!management*:!capsules*
  become: yes
  roles:
    - webconsole
    - leapp-upgrade

- name: Satellite clients
  hosts: all:!sat6*:!satellite*:!management*
  become: yes
  roles:
    - satellite-clients

- name: "Create ansible build environment"
  hosts: builder*
  become: yes
  roles:
    - ansible-builder

- name: Install Jboss Standalone
  hosts: jboss*
  become: yes
  roles:
    - jboss-standalone

- name: Configure Satellite
  hosts: sat6*
  environment: "{{ sat6_environment_vars }}"
  roles:
    - satellite-server
    - satellite-oscap

- name: Configure Satellite Capsules
  hosts: capsules*
  environment: "{{ sat6_environment_vars }}"
  roles:
    - satellite-capsule
    - satellite-oscap

- name: Configure Satellite Capsule Load Balancer
  hosts: capsule-lb*
  roles:
    - haproxy

- name: Configure Cloudforms Management Engine
  hosts: cloudforms*:cfme*
  roles:
    - cloudforms-server
    - firstboot
    - insights

- name: Configure Openstack Compute Nodes with HugePages, CPU pinning 
  hosts: osp10-computes
  roles:
    - { role: openstack, osp_mode: computes, cfme: false }

- name: Customize Openstack -  create networks, projects, users, and import glance images from nfs share
  hosts: osp10-controllers
  roles:
    - { role: openstack, osp_mode: controllers, cfme: true }

- name: Customize Openshift Container Platform nodes
  hosts: ose-cluster-node*
  roles:
    - { role: openshift, ocp_mode: nodes, cfme: false }

- name: Customize Openshift Container Platform with 2 additional nodes
  hosts: ose-cluster-master*
  roles:
    - { role: openshift, ocp_mode: controllers, cfme: true }

- name: Customize Ansible Tower
  hosts: tower*:10.55.102.156
  roles:
    - ansible-tower

- name: Network Bound Disk Encryption Client
  hosts: clevis*
  roles:
    - nbde-clevis-client

- name: Network Bound Disk Encryption Server
  hosts: tang-*
  roles:
    - nbde-tang-server

