---
- name: "Update /etc/rsyslog.d with template"
  template:
    src: zenoss.conf.j2
    dest: /etc/rsyslog.d/zenoss.conf
    mode: '0600'
  notify:
    - restart rsyslogd

- name: "Restore selinux context on  /etc/snmp/snmpd.conf"
  shell: restorecon -R /etc/rsyslog.d
  become: yes
