---
- name: "Tower Inventory Setup check"
  shell: |
    if [ -e "/opt/.tower-configed" ]
    then
      echo "true"
    else
      echo "false"
    fi
  register: towersetup
  become: true

- name: "Block add to Ansible Tower inventory"
  block:
    - name: "Get host id to add to the 'clevis-clients' Group Inventory"
      uri:
        url: "https://{{ tower_server }}/api/v2/hosts/?name={{ inventory_hostname }}"
        validate_certs: no
        method: GET
        user: "{{ tower_user }}"
        password: "{{ tower_pass }}"
        force_basic_auth: yes
        status_code: [200,202,204]
        body_format: json
      register: hostidcheck

    - name: "Set the host_id fact"
      set_fact:
        clevis_host_id: "{{ hostidcheck.json.results[0].id }}"

    - name: "Find Group Inventory for 'clevis-clients'"
      uri:
        url: "https://{{ tower_server }}/api/v2/groups/?search=clevis-clients"
        validate_certs: no
        method: GET
        user: "{{ tower_user }}"
        password: "{{ tower_pass }}"
        force_basic_auth: yes
        status_code: [200,202,204]
        body_format: json
      register: groupidcheck

    - name: "Set the group_id fact"
      set_fact:
        clevisgroup_id: "{{ groupidcheck.json.results[0].id }}"
  

    - name: "Add host to the 'clevis-clients' Group Inventory"
      uri:
        url: "https://{{ tower_server }}/api/v2/groups/{{ clevisgroup_id }}/hosts/"
        validate_certs: no
        method: POST
        body: >
          {
             "id": {{ clevis_host_id }}
          }
        user: "{{ tower_user }}"
        password: "{{ tower_pass }}"
        force_basic_auth: yes
        status_code: [201,202,204]
        body_format: json

    - name: "tower config complete"
      file:
        path: /opt/.tower-configed
        state: touch
        mode: 0444
      become: yes
  when: towersetup.stdout == "false"
