encrypted:
  device: sdb
  device_block: /dev/sdb
  device_name: encrypteddisk
  device_mountpoint: /mnt/encrypted
  device_fs: xfs
  device_size: "{{ aws_volume2_size | default(10,true) }}"
  passphrase: supersecret
