encrypted:
  device: nvme1n1
  device_block: /dev/nvme1n1
  device_lv: /dev/mapper/encryptedlv
  device_name: encrypteddisk
  device_mountpoint: /mnt/encrypted
  device_fs: ext4
  passphrase: supersecret
