---
- include: ose-get-token.yml
- name: "Check if CFME is up"
  shell: |
    ping -c 1 {{ cfme_server }} || true
  register: cfme_check

- name: "Add Openshift provider to CFME using the token acquired earlier"
  shell: |
    curl -k --user {{ cfme_creds }} \
    -i -X POST -H "Accept: application/json" \
    -d '{
          "type"      : "{{ cfme_type }}",
          "name"      : "{{ ose_name }}",
          "hostname"  : "{{ ose_server }}",
          "security_protocol"      : "{{ ose_security }}",
          "credentials" : {
            "userid"   : "{{ ose_add_user }}",
            "password" : "{{ ose_token }}"
          }' \
    https://{{ cfme_server }}/api/providers
  when: "'1 received' in cfme_check.stdout"
