---
- name: "Enable and start snmpd services"
  service:
    name: "{{ item }}.service"
    state: restarted
    enabled: yes
  become: true
  loop:
    - firewalld
    - snmpd

- name: "Restore selinux context on  /etc/snmp/snmpd.conf"
  shell: restorecon /etc/snmp/snmpd.conf
  become: yes
