---
- name: "Enabling needed repos for Openstack 10"
  shell: "subscription-manager repos --enable={{ item }}"
  with_items: "{{ openstack.enabled_repos }}"
  register: subscriberepos
  retries: 3
  until: subscriberepos.stdout.find("is enabled") != -1
  become: true

- name: "Install Openstack 10 Yum packages"
  yum:
    name: "{{ item }}"
    state: latest
  with_items: "{{ openstack.compute_packages }}"
  become: true

- name: "Configure compute nodes for Huge Pages"
  shell: |
    grubby --update-kernel=ALL --args="hugepagesz=2M hugepages=2048"
    grub2-install {{ openstack['hugepages']['device'] }}
    echo 'vm.nr_hugepages=6144' >> /etc/sysctl.conf
  args:
    chdir: /root
  become: true
  when: openstack['hugepages']['use']  == "yes"
  #ignore_errors: yes

- name: "Installing numactl"
  yum:
    name: "{{ item }}"
    state: latest
  with_items: "numactl"
  become: true
  when: openstack['cpupinning']['use']  == "yes"

- name: get the guest cpus we isolate for guest images
  shell: |
    numactl --hardware | grep 'node 0 cpus' | cut -d\: -f2| sed -e 's/ 0 1 //g' | sed -e 's/ /,/g'
  become: true
  register: guestcpus
  when: openstack['cpupinning']['use']  == "yes"

- name: update nova.conf cpu pinning values
  lineinfile:
    line: "vcpu_pin_set={{ guestcpus.stdout }}"
    dest: /etc/nova/nova.conf
    regexp: "^vcpu_pin_set=*"
    state: present
  when: openstack['cpupinning']['use']  == "yes"

- name: "Configure the system for cpu pinning"
  shell: |
    grubby --update-kernel=ALL --args="isolcpus={{ guestcpus.stdout }}"
    grub2-install {{ openstack['cpupinning']['device'] }}
  args:
    chdir: /root
  become: true
  when: openstack['cpupinning']['use']  == "yes"
  #ignore_errors: yes

- name: update nova.conf domain values
  lineinfile:
    line: "dhcp_domain={{ openstack['dhcp_domain'] }}"
    dest: /etc/nova/nova.conf
    regexp: "^dhcp_domain=*"
    state: present

#- name: "Enabling and restarting services openstack nova "
#  service:
#    name: "{{ item }}"
#    state: restarted
#    enabled: yes
#  with_items:
#    - openstack-nova-compute
#  become: true

- name: "Reboot to new settings. Back in 10 mins or so"
  shell: |
    shutdown -r +2 && sleep 2
  args:
    chdir: /root
  become: true
  when: ( openstack['hugepages']['use']  == "yes" ) or ( openstack['cpupinning']['use']  == "yes" )
