---
- include: "configure-osp-controllers.yml"
  when: osp_mode == 'controllers'

- include: "configure-osp-computes.yml"
  when: osp_mode == 'computes'

#- include: "fix-compute5.yml"
#  when: inventory_hostname == 'compute5.maskedadmins.com'
