---
- name: restart haproxy
  service:
    name: haproxy
    state: restarted
    enabled: true
  become: yes

- name: restart firewalld
  service:
    name: firewalld
    state: restarted
    enabled: true
  become: yes
