---
- name: "Add Tower provider"
  shell: |
    curl -k --user {{ cfme_creds }} \
    -i -X POST -H "Accept: application/json" \
    -d '{
          "type"      : "{{ cfme_type }}",
          "name"      : "{{ tower_name }}",
          "hostname"  : "{{ tower_server }}",
          "security_protocol"      : "{{ tower_security }}",
          "credentials" : {
            "userid"   : "{{ tower_user }}",
            "password" : "{{ tower_pass }}"
          }' \
    https://{{ cfme_server }}/api/providers
  ignore_errors: yes
