---
- name: "Add Openstack provider to CFME"
  hosts: cloudforms.dev.maskedadmins.com
  vars:
    cfme_user: "admin"
    cfme_pass: "smartvm"
    cfme_server: "{{ ansible_hostname }}"
    cfme_project: redhat-lab
    compute_resources:
      - name: 'OSP8'
        description: 'Openstack 8 Redhat Lab'
        user: 'dtaylor'
        pass: "{{ ipmi_pass }}"
        security: non-ssl
        server: "{{ osp8_controller }}"
      - name: 'OSP10'
        description: 'Openstack 10'
        user: dtaylor
        pass: CHANGEPASS
        security: non-ssl
        server: "{{ osp10_controller }}"
  tasks:
    - name: "Use the API to add Openstack provider to CFME"
      shell: |
        curl -k --user {{ cfme_user }}:{{ cfme_pass }} \
        -i -X POST -H "Accept: application/json" \
        -d "{
              \"type\"      : \"ManageIQ::Providers::Openstack::CloudManager\",
              \"name\"      : \"{{ item.name }}\",
              \"hostname\"  : \"{{ item.server }}\",
              \"ipaddress\" : \"{{ item.server }}\",
              \"security_protocol\"      : \"{{ item.security }}\",
              \"credentials\" : {
                \"userid\"   : \"{{ item.user }}\",
                \"password\" : \"{{ item.pass }}\"
              }
        }" \
        https://{{ cfme_server }}/api/providers
        sleep 5
      with_items: "{{ compute_resources }}"
