---
- name: "Cloudforms is running check"
  shell: |
    if [ -e "/var/run/httpd/httpd.pid" ]
    then
      echo "true"
    else
      echo "false"
    fi
  register: cfmecheck

- name: "Block to configure CFME"
  block:
  - name: "Configure CFME"
    shell: |
      TERM=vt100 appliance_console_cli -v --internal --dbdisk /dev/vdb --region 0 --password {{ cfme_pass }}
    args:
      creates: /var/run/httpd/httpd.pid
    become: true

  rescue:
  - name: "Try again to configure CFME"
    shell: |
      lvremove -f /dev/vg_pg/lv_pg
      vgremove -f vg_pg
      pvremove -f /dev/vdb1
      echo -e "rm 1\nquit" | parted /dev/vdb1
      partprobe
      TERM=vt100 appliance_console_cli -v --internal --dbdisk /dev/vdb --region 0 --password {{ cfme_pass }}
    args:
      creates: /var/run/httpd/httpd.pid
    become: true

  always:
  - name: "Reboot server"
    shell: |
      shutdown -r +1 && true
    become: true

  - name: "Wait for host to reboot"
    local_action: wait_for port=22 host="{{ ansible_ssh_host | default(inventory_hostname) }}" search_regex=OpenSSH delay=240
    
  - name: "Wait for CFME to start"
    local_action: wait_for port=443 host="{{ ansible_ssh_host | default(inventory_hostname) }}" delay=240

  when: cfmecheck.stdout == 'false'

- include: "add-openstack-to-cfme.yml"
